### ISSUE TITLE
Parallel file reader

### ISSUE THREAD

**Issue by cpockrandt** [seqan/seqan3#1162]
I'm currently writing a tool that reads large fastq-files and iterates over all reads once (just like a read mapper). Unfortunately parallelizing is not really convenient with OpenMP since you do not know the number of reads in advance. This sounds like a producer-consumer-pattern.

I was wondering if you thought about this problem and whether we shall offer a parallel file reader in SeqAn3. It's quite a basic and important feature for many applications and a hassle if users have to write it themselves. Maybe there is already some fancy way in SeqAn3 that I didn't see or think about?

**Comment by h-2** [comment]
What do you mean by "parallel file reader"? Do you mean asynchronous I/O? Or do you want to read different parts of the file in parallel? The latter is never advisable, because reading from disk is inherently non-parallel, for hard-drives the system can only be at one place at the same time.

Regarding Async I/O, that is something I will be working on for 3.0.1.

**Comment by cpockrandt** [comment]
No, I'm not talking about going over the file in parallel. I mean buffering and multiple threads going over the buffered reads in parallel. You usually want to process all the reads in parallel but you don't want to keep them all in memory at the same time.

**Comment by h-2** [comment]
What we are planning is for the file to read into the buffer into the background so that I/O happens in a separate thread in the background while processing happens in the foreground. However this does not mean that you can iterate over the file with multiple threads in parallel. That would imply that the file needs to know which thread still needs which part of the buffer. This is not possible with the current design and I can hardly think of a design where it wouldn't incur a significant performance penalty.

In general it will still hold that incrementing the file iterator will invalidate any references to the previous record. The design I have sketched in my head might however allow setting the size of the underlying buffer and if everything works as planned all previous `n` records in the buffer will remain valid. So if your parallisation is ordered (e.g. 8 threads will always work on one record each and every thread  gets a new record only when all threads are finished) this will still work. Regular parallelisation where one thread might be faster than another and requests for new records happen irregularly  won't be possible with this approach.

However, thinking about the problem I just came up with a rather simple "solution".
We could make a `view::thread_safe` who
  * stores a mutex and whose iterators have scoped_locks
  * dereference moves out the underlying value at the position and also increments

If you pipe your file into this your threads could independently access the view and always get a new record by value. Note that locking has substantial overhead, though. Especially if records are small you might be better of not doing locking and just buffering yourself for each thread... I will discuss this design with @rrahn at the end of July.

**Comment by cpockrandt** [comment]
> What we are planning is for the file to read into the buffer into the background so that I/O happens in a separate thread in the background while processing happens in the foreground. However this does not mean that you can iterate over the file with multiple threads in parallel. That would imply that the file needs to know which thread still needs which part of the buffer. This is not possible with the current design and I can hardly think of a design where it wouldn't incur a significant performance penalty.

If you have one thread that buffers some reads into a concurrent queue and N-1 threads dequeing and processing the reads, this should always be faster than a sequential program (assuming that processing the reads is somewhat expensive like aligning). This wouldn't required any ordered parallelization.

> However, thinking about the problem I just came up with a rather simple "solution".
We could make a view::thread_safe [...]

That could make sense. You should chunk the reads in your file (e.g., `| ranges::view::chunk(1000)`) so that you only lock and retrieve reads every thousand records to keep the overhead small.

**Comment by cpockrandt** [comment]
I forgot to add that your plan might not be as easy. You can't use OpenMP when reading the file straight forward (not even with locking) since you do not know the number of iterations. The iterator only supports `operator!=`, not ordered ones such as `operator<`. If you parallelize a for-loop, OpenMP requires something like `operator<` instead of `operator!=` in the for-loop condition.

    for (auto it = file_in.begin(); it < file_in.end(); it++)

**Comment by rrahn** [comment]
I would always keep these things separate. Like don‘t try to make something parallel that is an inherently sequential problem. 

In general what we should think of are two scenarios. A) the user want‘s to read chunks of records, process the chunk and fetch the next chunk asynchronously. B) as discussed the user asynchronously adds the read records to a queue and consumer threads will process the work. I think both solutions can be made fairly easy with either bulk_executors or regular executors. If this would be still to low level one could provide wrapper functions that can deal with common use cases.

**Comment by h-2** [comment]
@cpockrandt We have merged the Async Input support. Can you try it out and see if it works as expected?

**Comment by h-2** [comment]
(I will close this, but feel free to continue discussing or re-open if the PR did not address what you meant)
