### ISSUE TITLE
Where to place `test/` utility functions?

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#124]
#120 introduced `/test/include/seqan3_test/tmp_filename.hpp`

I would like to discuss where files should life and what the namespace is.

We could do it in the following ways:
* put it into  `/include/seqan3/test/`
* put it into  `/include/seqan3_test/`
* put it into  `/test/include/seqan3/`
* put it into  `/test/include/seqan3_test/`

I think the namespace `seqan3::test` is already good.

**Comment by h-2** [comment]
I would put them in `/test/include/seqan3/`

**Comment by rrahn** [comment]
I am also now for changing it to `/test/include/seqan3/`
At the beginning, I wasn't sure, because of having the same include name for library and test code, but then again we have the special `test` namespace, which makes the include name obsolete, I think.
I will change this now for the current PR #120.

**Comment by rrahn** [comment]
Ok, after a fruitful 🍌 discussion with @marehr, it seems still better to leave the original idea of using `/test/include/seqan3/test` 
```cpp
#include <seqan3/test/xyz.hpp>
#include <seqan3/range/view.hpp>
```
or `/test/include/seqan3_test` 
```cpp
#include <seqan3_test/xyz.hpp>
#include <seqan3/range/view.hpp>
```
Both versions are much better for a destination of test utility functionality and stuff from the main repository. 
The question remains of how to choose the namespace.
Either:
```cpp
namespace seqan3::test
{
 ...
}

// Usage:
using namespace seqan3;
do_something ...
test::tmp_file_name ...
```
or 
```cpp
namespace seqan3_test
{
 ...
}

// Usage:
using namespace seqan3;
do_something ...
::seqan3_test::tmp_file_name ...
```
So after considering this I suggest we use the first approach.

**Comment by h-2** [comment]
> Ok, after a fruitful banana discussion with @marehr, it seems still better to leave the original idea of using /test/include/seqan3/test
> or /test/include/seqan3_test

OK, I have not strong feelings about it, but would prefer `/test/include/seqan3/test`

> The question remains of how to choose the namespace.

A sub-namespace is definitely preferable, because you can call stuff from the immediate parent namespace (in our case `seqan3`) without prefixing it, whereas with a separate namespace you would need lot's of `seqan3::` ...

Also this should be in line with the above decision. (if it's `seqan3/test` it should be `seqan3::test`, if it's `seqan3_test` it should also be `seqan3_test`),

**Comment by marehr** [comment]
Okay we came to the conclusion that `/test/include/seqan3/test/` and `namespace seqan3::test` is the right place.

#120 already reflects this change, thus closing this ticket.
