### ISSUE TITLE
<=> operator makes <, >, <=, >=, ==, != redundant

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#126]
We can reduce a lot of code within the alphabet module. Because most alphabets are trivial comparable.

------
http://en.cppreference.com/w/cpp/language/default_comparisons:

> Provides a way to request the compiler to generate consistent relational operators for a class.
>
> In brief, a class that defines operator<=> automatically gets compiler-generated operators ==, !=, <, <=, >, and >=. A class can define operator<=> as defaulted, in which case the compiler will also generate the code for that operator. 

```cpp
class Point {
 int x;
 int y;
public:
 auto operator<=>(const Point&) const = default;
 // ... non-comparison functions ...
};
 
Point pt1, pt2;
if (pt1 == pt2) { /*...*/ } // ok
set<Point> s; // ok
s.insert(pt1); // ok
if (pt1 <= pt2) { /*...*/ } // ok, makes only a single call to <=>
```

**Comment by marehr** [comment]
Created a [card](https://github.com/seqan/seqan3/projects/5#card-7576543) which can be later turned into an issue when c++20 is a less "new" thing

**Comment by h-2** [comment]
Also we are not targeting C++20 anyway so this won't be relevant until SeqAn-4 I think...

**Comment by marehr** [comment]
We have so many dependencies that will ship in c++20 (concepts, file-ts, ranges) that we will bump the requirement to c++20 naturally.

**Comment by h-2** [comment]
> We have so many dependencies that will ship in c++20 (concepts, file-ts, ranges) that we will bump the requirement to c++20 naturally.

I disagree completely. We definitely need to discuss this. Right now our requirement is GCC-7 + libraries. If other compilers catch up we will support them (and possibly via their c++20 flag) but that doesn't mean we are dropping support for GCC7 (which means we cannot introduce newer stuff).

If we want people to use our library we need to offer some kind of stability in the build environment. Dropping every compiler except GCC7 was already a huge wager, but IMO it was worth it, because Concepts are fundamental to SeqAn3. I agree that the spaceship operator is cool and I would like to have it, but it in no way justifies dropping GCC7, when not even GCC7 has been deployed to Linux distributions widely!!
