### ISSUE TITLE
debug_stream needs to include <iostream> not just forwards

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1423]
Otherwise you get crashes when trying to print something.

**Comment by eseiler** [comment]
This line here?

https://github.com/seqan/seqan3/blob/59844323c54121052a686dfe0d6cd7e95b21b8f4/include/seqan3/core/detail/debug_stream_type.hpp#L15

I can probably combine this with revising the \brief of the debug stream files.

**Comment by h-2** [comment]
No, it is important that `debug_stream_type.hpp` only include `<iosfwd>`, so that our library headers that include this don't pull in iostream. But `debug_stream.hpp`, the header offered to users and test should include full `<iostream>`.

**Comment by marehr** [comment]
Just to clarify: It crashes if you don't include `<iostream>`, right?

**Comment by h-2** [comment]
> Just to clarify: It crashes if you don't include <iostream> , right?

Yep, because you `externed` things the compiler will not give an error, but instead the application will crash.

**Comment by Irallia** [comment]
@seqan/core We closed https://github.com/seqan/seqan3/issues/1456, what do we do with this one?

**Comment by smehringer** [comment]
This is still an issue, I traced it down to the following:

cereal somewhere includes `<iostream>` and cereal is included somewhere on the path from `debug_stream.hpp`. That's why we never reproduced the error because we have cereal always available in our tests/snippets.

So to fix this, add `#include <iostream>` to `seqan3/core/debug_stream.hpp`  :)
