### ISSUE TITLE
[Search] `search()` should always return a range of `search_result`

### ISSUE THREAD

**Issue by eseiler** [seqan/seqan3#1434]
**Level 1 - Easy**

A call to `search()` should return a `search_result` for each hit. It contains:
* iterator
* sequence (if requested)
* position (if requested)
* errors (ins, del, sub)
* query_id

- [x]  Create `search_result`
- [x]  Return `search_result` in search/algorithm/detail/search.hpp:126
- [ ] test search result
- [ ] document the search result
- [ ] adapt tutorial if applicable

**Comment by h-2** [comment]
I would propose the following:
```
query_id()                     
subject_id()                   !without_positions
subject_begin_position()       !without_positions
subject_end_position()         !without_positions
subject_subrange()             (!without_positions and text given) OR compute on demand¹
substitutions()
insertions()
deletions()
index_cursor()
```

Positions are computed unless the user specifies `seqan3::search_cfg::result{seqan3::search_cfg::without_positions}`.
Is it correct to assume that the error can be counted for free? Otherwise we need an option for them, too.

For the subject_subrange we can can return `views::slice` when the text is provided and the positions are computed. Otherwise, we could have the function create and return a `std::vector` on demand by doing voodoo with the iterator (no need to configure this).

**Comment by smehringer** [comment]
Outstanding design decisions:

1. **Which members (with names) will the search struct provide?**

    Information that we already have, where the naming needs to be decided:
    * query_id()                     
    * subject_id() / sequence_id() / reference_id()
    * subject_begin_position() / sequence_pos() / begin_position()
    * index_cursor() / cursor()

     Stuff that might be valuable:
    * subject_end_position()
    * subject_subrange()
    * substitutions()
    * insertions()
    * deletions()

2. **Which of the above is included by default / always included / included by configuration?**
    Note: 
    (1) One cursor always points to multiple positions (intervals). So if we always include the cursor, we have to copy it into every result struct that has a position which comes from that cursor, and
    (2) Two cursors might point to overlapping intervals. So when "uniquifying" the result there will only be a single cursor for a single position and we need to decide which one.

**Comment by smehringer** [comment]
#### Resolution:

1. **Names**
   * query_id()
   * reference_id()
   * reference_begin_position()
   * index_cursor()
   for the rest we plan this if we have an actual use case

2. **Configuration**
   Always included:
   * query_id()
   We will either output cursor or text positions!
   Only with positions:
   * reference_id()
   * reference_begin_id()
   Only with cursor:
   * index_cursor

**Comment by h-2** [comment]
Just FYI, this is my opinion and what I wrote in my thesis:

---

![image](https://user-images.githubusercontent.com/2996863/78258792-41e6c200-74eb-11ea-9860-d33c64774351.png)

---

I think we decided before that we always include those config elements that are free to compute. This means the cursor would always be included, because it is always available. It is entirely stored on the stack so it is cheap to copy it to all of it results.

We also discussed before that `subject_end_position` could be relevant when indels are allowed.

**Comment by smehringer** [comment]
> I think we decided before that we always include those config elements that are free to compute. This means the cursor would always be included, because it is always available. 

->

> Note:
(1) One cursor always points to multiple positions (intervals). So if we always include the cursor, we have to copy it into every result struct that has a position which comes from that cursor, and
(2) Two cursors might point to overlapping intervals. So when "uniquifying" the result there will only be a single cursor for a single position and we need to decide which one.

**Comment by h-2** [comment]
I think that you usually want either the positions or the cursor, but I don't see how providing the cursor is a problem. It means reducing configuration options...

> (1) One cursor always points to multiple positions (intervals). So if we always include the cursor, we have to copy it into every result struct that has a position which comes from that cursor, 

>> It is entirely stored on the stack so it is cheap to copy it to all of it results.

> (2) Two cursors might point to overlapping intervals. So when "uniquifying" the result there will only be a single cursor for a single position and we need to decide which one.

Taking either is better than taking neither?

Anyway, your decision, just thought I'd let you know what I thought.

**Comment by rrahn** [comment]
> Anyway, your decision, just thought I'd let you know what I thought.

What is the additonal benefit of having the cursor? Is there anything I can do with it in addition to having the positions?

**Comment by smehringer** [comment]
> Taking either is better than taking neither?

Well I could not think of a use case where you need both, and then "neither" has better performance because I don't copy a 50-byte iterator every time?

**Comment by h-2** [comment]
> What is the additonal benefit of having the cursor? Is there anything I can do with it in addition to having the positions?

You can sort your collection of results by identity of the cursor which equates to identity of the subject-subrange (but is more efficient to compare). You can also call count on the cursor to get the "duplicity" of a result. That might be helpful for post-processing results, e.g. sorting or filtering.

> Well I could not think of a use case where you need both, 

I agree that it is probably not common. And one could argue that it is more confusing to have both if the use-cases are indeed distinct. But on the other hand an additional config element also increases complexity.
There is good arguments for either, I don't have strong feelings about this, I just thought my proposal was more in line with the things I remember we discussed, but I might have selective memory here :wink: 

> and then "neither" has better performance because I don't copy a 50-byte iterator every time?

That's six machine words of stack storage? I would be surprised if that has any influence, but I am not sure. 

In any case, I don't want to distract you with this for too long. I am sure there are more important things!

**Comment by smehringer** [comment]
You are right that we discussed always including members that are a "no-op" to include anyway but since the search right now is laid out to return either the cursor or the positions it would actually require more work, brain and discussions to always include the cursor (without naming them all here). So for now, it saves time to allow "either-or" for now without anything preventing us to add this later on.

**Comment by rrahn** [comment]
See seqan/product_backlog#52
