### ISSUE TITLE
Argument Parser throws wrong error

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#1544]
if you have a valid option `--foo` and a non-existant option `--foo-bar` and give both a la `--foo X --foo-bar Y` the arg parser will print:
```
Option -f/--foo is no list/container but specified multiple times
```
Instead of just saying that `--foo-bar` does not exist.

**Comment by marehr** [comment]
Example code?

**Comment by smehringer** [comment]
This error occurs because of the following ambiguity:

We support giving the option value directly after the option `-Soption_value` or `-foooption_value`?...(I am currently wondering why..). That\s why we only do prefix checks with the option ids.

I guess this can only be circumvented if we sort the ids by size to check long ids before short ones.

**Comment by rrahn** [comment]
Maybe I am missing something, but we allow `-svalue` and `-s value` as being in line with the POSIX guidelines. However, there I can't see anything about long option names, which seems to be an extension by [GNU](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html). There, however, they explicitly mention to write long option values as `--short=value`. So this is what seems to be missing. That means we can enforce both `--short value` and `--short=value` without ambiguity and could point to the GNU extension of the POSIX option standard.

**Comment by rrahn** [comment]
@marehr here is what the issue is about:

The current call too a program should correctly determine the unknown option `foo-bar`:
```console
./my_app --foo -bar --foo-bar foobar
```
The app only knows about option `foo` but nothing about `foo-bar`, but thinks that `--foo-bar` is the same as `--foo -bar`, which is allowed for the short option notation. The fix would be to only allow long options as `--foo=-bar` or `--foo -bar`. So separation or equal sign.

**Comment by h-2** [comment]
Yes, absolutely. I am surprised that `--longvalue` works, only `--long value` and `--long=value` should.

**Comment by smehringer** [comment]
oh ok. I missed that. I'll change it accordingly
