### ISSUE TITLE
error when reading bam files with default fields.

### ISSUE THREAD

**Issue by simonsasse** [seqan/seqan3#1616]
### How to repeat the problem
```cpp
#include <seqan3/io/alignment_file/all.hpp>
#include <seqan3/argument_parser/all.hpp>
#include <seqan3/core/debug_stream.hpp>
#include <string>

int main(int argc, char const *argv[])
{
	//initialize file_path_parser
	seqan3::argument_parser file_path_parser{"Alignmentfile_Conversion", argc, argv};

	std::string input_file{};
	std::string output_file{};

	file_path_parser.add_option(input_file, 'i', "in-file", "Input the complete Path of the Alignment-Inputfile including Filename and Suffix.",
								seqan3::option_spec::REQUIRED, seqan3::input_file_validator{});
    file_path_parser.add_option(output_file, 'o', "out-file", "Input the wished Path of the Alignment-Outputfile including Filename and Suffix.",
								seqan3::option_spec::REQUIRED, seqan3::output_file_validator{});

	try
	{
		file_path_parser.parse();
	}
	catch(seqan3::parser_invalid_argument const & ext)
	{
		seqan3::debug_stream<<"[Parsing error] "<<ext.what() <<'\n';
		return -1;
	}
	//write sequence to new output_file.
	seqan3::alignment_file_output{output_file} = seqan3::alignment_file_input{input_file};
	return 0;
}
```
### Expected behaviour

Sam File should be written.

### Actual behaviour
```
terminate called after throwing an instance of 'std::logic_error'
  what():  Access is not allowed because there is no sequence information.
[1]    3365 abort      ./alignment_file_conversion -i ../source/data/IonXpress_020_rawlib.b37.bam -o
```

**Comment by eseiler** [comment]
Can you please attach the BAM file?

The error is thrown by an implementation detail and it should happen if you try to access the alignment without a alignment being available (because of missing reference information).

Anyway, it would be nicer to fail with a more helpful error message for the user.

**Comment by smehringer** [comment]
I already know why the error occurs. Our default fields include `field::alignment` but without reference information (which need to be given on construction) the aligned reference sequences is a dummy sequence that cannot be accessed.

There are several ways of dealing with this
1. We need to implement a to_cigar conversion that does not access the aligned sequence but only asks `is_gap`. This would be fine for the dummy sequence with a gapped decorator and avoid the error.
2. We use the `field::cigar` instead of `field::alignment` which does not have this issue. This would also be more similar to the SAM standard. (If we choose this option I would actually prohibit to read the `field::alignment` without reference information.) 
3. Make the error message more helpful telling the user to include reference information if he wants to write the alignment information
