### ISSUE TITLE
pairwise_align fails on large sequences

### ISSUE THREAD

**Issue by ibharvey** [seqan/seqan3#1619]
## Platform

  - SeqAn version: Current master node
  - Operating system: Ubuntu 18.04.4
  - Compiler: GCC 7.4.0

## Question

How do I allocate enough memory to the sequence_file_input so that seqan3 can align large sequences pulled from a file? I've attached the basic problem I'm running into, where very small sequences can be loaded and aligned fine, but the program throws std::bad_alloc if the sequence is >100kbp.

https://github.com/ibharvey/seqan3_cmake_error

`./build/src/program test/test_pass.fa` 
vs
`./build/src/program test/test_fail.fa`

**Comment by rrahn** [comment]
Hi @ibharvey thanks for writing us. 
The problem here is, that the if you want to compute the alignment the entire trace matrix needs to be allocated which consumes for sequences of size 100k already 100kB^2 = 10Gb of memory. We have planned for the future several techniques to keep the memory footprint low for large sequence alignments. But there are no immediate plans to work on this soon. In the meanwhile, you could try to use a band in case you know that the sequences are somewhat similar. Thus, a relatively large band of size 10kB could already reduce the memory to 1GB. Or if you do not need the trace but are only interested in the score you can configure the alignment to only compute this. Then no memory for the trace matrix will be allocated at all.

So in your example you would change this line
```cpp
    auto config =   seqan3::align_cfg::mode{seqan3::global_alignment} | 
                    seqan3::align_cfg::aligned_ends{seqan3::free_ends_all} |
                    seqan3::align_cfg::scoring{seqan3::nucleotide_scoring_scheme
                        {
                            seqan3::match_score{4},
                            seqan3::mismatch_score{-2}
                        }
                    } |
                    seqan3::align_cfg::gap{seqan3::gap_scheme{seqan3::gap_score{-4}}} |
                    seqan3::align_cfg::result{seqan3::with_alignment};
```

to 
```cpp
    auto config =  seqan3::align_cfg::mode{seqan3::global_alignment} | 
                    seqan3::align_cfg::aligned_ends{seqan3::free_ends_all} |
                    seqan3::align_cfg::scoring{seqan3::nucleotide_scoring_scheme
                        {
                            seqan3::match_score{4},
                            seqan3::mismatch_score{-2}
                        }
                    } |
                    seqan3::align_cfg::gap{seqan3::gap_scheme{seqan3::gap_score{-4}}} |
                    seqan3::align_cfg::result{seqan3::with_score};
```
Or in case you want to add a band:
```cpp
    auto config =  seqan3::align_cfg::mode{seqan3::global_alignment} | 
                    seqan3::align_cfg::aligned_ends{seqan3::free_ends_all} |
                    seqan3::align_cfg::scoring{seqan3::nucleotide_scoring_scheme
                        {
                            seqan3::match_score{4},
                            seqan3::mismatch_score{-2}
                        }
                    } |
                    seqan3::align_cfg::band{seqan3::static_band{
                            seqan3::lower_bound{-5000}, 
                            seqan3::upper_bound{5000}}
                    } |
                    seqan3::align_cfg::gap{seqan3::gap_scheme{seqan3::gap_score{-4}}} |
                    seqan3::align_cfg::result{seqan3::with_alignment};
```

Would this help you for now?

**Comment by ibharvey** [comment]
Thanks @rrahn , that worked great.

**Comment by rrahn** [comment]
Please feel free to reopen or create a new one if you encounter any other issues.
