### ISSUE TITLE
[BUG] Take_until and reverse view combined are a sized_range, but should not be 

### ISSUE THREAD

**Issue by MitraDarja** [seqan/seqan3#1946]
## Description

Combining the view take_until with reverse leads to the following problem: If used on a std::vector or an seqan3::bitcompressed_vector, they appear to be a sized_range, but are not and a direct call to std::ranges::size() will result in an error message. This can cause a problem, eg. when using the minimiser view with two ranges.

### How to repeat the problem

```cpp
auto stop_at_t = seqan3::views::take_until([] (seqan3::dna4 const x) { return x == 'T'_dna4; });

std::vector<seqan3::dna4> text1{'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4, 'C'_dna4, 'G'_dna4, 'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4,
            'T'_dna4, 'T'_dna4, 'A'_dna4, 'G'_dna4};
auto v = text1 | stop_at_t | std::views::reverse;
 std::cout << std::ranges::sized_range<decltype(v)>; // prints 1, should be 0
auto va = text1 | stop_at_t;
 std::cout << std::ranges::sized_range<decltype(va)>; //  prints 0 as expected

std::list<seqan3::dna4> text2{'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4, 'C'_dna4, 'G'_dna4, 'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4,
            'T'_dna4, 'T'_dna4, 'A'_dna4, 'G'_dna4};
auto v2 = text2 | stop_at_t | std::views::reverse;
 std::cout << std::ranges::sized_range<decltype(v2)>; // prints 0 as expected
```

I believe the reason for this behaviour is std::reverse, which for some reason assumes that ` text1 | stop_at_t` is a sized_range, because it is working if the text is not a sized range, I can only assume that std::reverse is not considering the take_until but only looks at the underlying range.

**Comment by rrahn** [comment]
Mhmm, std::list is a sized range and also the reverse view never looks into the first range because it cannot know the type of it. There is no guarantee that any view exposes it’s underlying range so the reverse view cannot assume that this information is available. Can you please specify the stop_at_t type in order to reproduce the error? 

According to the standard the reverse view calls only size if the underlying range (take_until) is sized:

```cpp
constexpr auto size() requires sized_range<V> {
      return ranges::size(base_);
    }
    constexpr auto size() const requires sized_range<const V> {
      return ranges::size(base_);
    }
```
Our take_until Code uses the size definition of the view_interface:

```cpp
constexpr auto size() requires forward_range<D> &&
      sized_sentinel_for<sentinel_t<D>, iterator_t<D>> {
        return ranges::end(derived()) - ranges::begin(derived());
      }
    constexpr auto size() const requires forward_range<const D> &&
      sized_sentinel_for<sentinel_t<const D>, iterator_t<const D>> {
        return ranges::end(derived()) - ranges::begin(derived());
      }
```

So can you check whether `sized_sentinel_for<sentinel_t<D>, iterator_t<D>>` with D being the take_until view is true? And also if any other definition of ranges::size can be compiled? v.size(), unqualified size(v), end(v) - begin(v). For all the combinations above?

**Comment by MitraDarja** [comment]
Sized_Sentinel_For_Test:
```cpp
auto stop_at_t = seqan3::views::take_until([] (seqan3::dna4 const x) { return x == 'T'_dna4; });

std::vector<seqan3::dna4> text1{'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4, 'C'_dna4, 'G'_dna4, 'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4,
            'T'_dna4, 'T'_dna4, 'A'_dna4, 'G'_dna4};
auto v = text1 | stop_at_t | std::views::reverse;
 std::cout <<  std::sized_sentinel_for<std::ranges::sentinel_t<decltype(v)>, std::ranges::iterator_t<decltype(v)>>; // prints 1
auto va = text1 | stop_at_t;
 std::cout <<  std::sized_sentinel_for<std::ranges::sentinel_t<decltype(va)>, std::ranges::iterator_t<decltype(va)>>; //  prints 0

std::list<seqan3::dna4> text2{'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4, 'C'_dna4, 'G'_dna4, 'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4,
            'T'_dna4, 'T'_dna4, 'A'_dna4, 'G'_dna4};
auto v2 = text2 | stop_at_t; //| std::views::reverse;
 std::cout << std::sized_sentinel_for<std::ranges::sentinel_t<decltype(v2)>, std::ranges::iterator_t<decltype(v2)>>; // prints 0
```

Test size()
Does not compile: "error: no matching function for call to ‘ranges::reverse_view<seqan3::detail::view_take_until<ranges::ref_view<std::vector<seqan3::dna4> >, minimiser_test_combinability_Test::TestBody()::<lambda(seqan3::dna4)>, false, false> >::size()’ "
```cpp
auto stop_at_t = seqan3::views::take_until([] (seqan3::dna4 const x) { return x == 'T'_dna4; });

std::vector<seqan3::dna4> text1{'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4, 'C'_dna4, 'G'_dna4, 'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4,
            'T'_dna4, 'T'_dna4, 'A'_dna4, 'G'_dna4};
auto v = text1 | stop_at_t | std::views::reverse;
v.size();
```
Does not compile: "error: no matching function for call to ‘seqan3::detail::view_take_until<ranges::ref_view<std::vector<seqan3::dna4> >, minimiser_test_combinability_Test::TestBody()::<lambda(seqan3::dna4)>, false, false>::size()’"
```cpp
auto stop_at_t = seqan3::views::take_until([] (seqan3::dna4 const x) { return x == 'T'_dna4; });

std::vector<seqan3::dna4> text1{'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4, 'C'_dna4, 'G'_dna4, 'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4,
            'T'_dna4, 'T'_dna4, 'A'_dna4, 'G'_dna4};
auto va = text1 | stop_at_t;
va.size();
```
Does not compile: "error: no matching function for call to ‘ranges::reverse_view<seqan3::detail::view_take_until<ranges::ref_view<std::__cxx11::list<seqan3::dna4> >, minimiser_test_combinability_Test::TestBody()::<lambda(seqan3::dna4)>, false, false> >::size()’
```cpp
auto stop_at_t = seqan3::views::take_until([] (seqan3::dna4 const x) { return x == 'T'_dna4; });

std::list<seqan3::dna4> text2{'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4, 'C'_dna4, 'G'_dna4, 'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4,
            'T'_dna4, 'T'_dna4, 'A'_dna4, 'G'_dna4};
auto v2 = text2 | stop_at_t | std::views::reverse;
v2.size();
```

end(v) - begin(v) Test:
Compiles:
```cpp
    std::vector<seqan3::dna4> text1{'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4, 'C'_dna4, 'G'_dna4, 'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4,
            'T'_dna4, 'T'_dna4, 'A'_dna4, 'G'_dna4};
auto v = text1 | stop_at_t | std::views::reverse;
 std::cout <<  end(v) - begin(v); // prints 3
```
Does not compile:
```cpp
std::vector<seqan3::dna4> text1{'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4, 'C'_dna4, 'G'_dna4, 'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4,
            'T'_dna4, 'T'_dna4, 'A'_dna4, 'G'_dna4};
auto va = text1 | stop_at_t;
 std::cout <<  end(va) - begin(va); 
```
Does not compile:
```cpp
std::list<seqan3::dna4> text2{'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4, 'C'_dna4, 'G'_dna4, 'A'_dna4, 'C'_dna4, 'G'_dna4, 'T'_dna4,
            'T'_dna4, 'T'_dna4, 'A'_dna4, 'G'_dna4};
auto v2 = text2 | stop_at_t | std::views::reverse;

 std::cout << end(v2) - begin(v2); 
```

What is unqualified size(v)? And how would I implement that? Like this the compiler says that unqualified  was not declared. :see_no_evil:

**Comment by rrahn** [comment]
A free function is called qualified if we prepend it with a namespace: `seqan3::free_function(...)`. We call the free function unqualified without the namespace `free_function(...)`. In the latter the compiler tries to find a suitable candidate based on the parameters given to the function and other factors, something we call Argument Dependent Lookup (ADL).

**Comment by rrahn** [comment]
Wow, this is fun: 

reverse view begin returns:
```cpp
make_reverse_iterator(ranges::next(ranges::begin(base_), ranges::end(base_)))
```

reverse view end returns:
```cpp
make_reverse_iterator(ranges::begin(base_))
```
So in this case, within the reverse view our view will be promoted to a common range since `ranges::next(ranges::begin(base_), ranges::end(base_))` returns an iterator pointing to the early end of the take_until view. This is the same type as used for the end of the reverse view which uses the begin of the underlying range. Now, our inherited iterator base adds the difference operator to the view based on the underlying range: in case of std::vector this is true and in case of std::list this is not. Thus, we get a sized sentinel for the reversed take until if we put it into a reverse view.

**Comment by marehr** [comment]
In (hopefully) simpler terms:

`take_until` can be sized again, if someone converts this to a common range. In order to get a common range, you need to find the "end" (that means iterating over the complete range from "start" to "end") in `take_until`. If you found the "end", `seqan3::views::take_until` is basically the same as writing `std::views::take(distance)` where `distance` is the distance between the begin and end iterator. 

Since `std::views::take` preserves sizedness of the underlying range, `seqan3::views::take_until | std::views::reverse` does too, because it is semantically the same as writing `std::views::take(distance) | std::views::reverse` where `distance` is the first position of the predicate that evaluates to true.

So this is unfortunately not your bug, and (surprisingly) expected behaviour.

**Comment by MitraDarja** [comment]
I am still a bit confused by this, how is this then a sized range, if you cannot call the size-Operator for `take_until | std::reverse`. Isn't the whole point of a sized_range, that the range can return a size?

**Comment by marehr** [comment]
This compiles:

```c++
#include <ranges>
#include <vector>

int main()
{
    std::vector<int> v{};
    auto view = v | std::views::take_while([](int x) { return x < 5; });
    auto reverse_view = std::views::all(v) | std::views::reverse;

    static_assert(std::ranges::sized_range<std::vector<int>>);
    static_assert(!std::ranges::sized_range<decltype(view)>);
    static_assert(std::ranges::sized_range<decltype(reverse_view)>);

    return std::ranges::size(v) + std::ranges::size(reverse_view);
}
```

https://godbolt.org/z/gGtmL5

With ranges library and with the standard, what code did not compile for you?  Are you sure that the underlying container that did not work was a `std::vector`, because it should work?

Ah you used `v2.size();`, please use the proper generic interface `std::ranges::size`. Since there is no guarantee that every view  defines a size function. `std::ranges::sized_range` is defined true if you can use `std::ranges::size` (https://eel.is/c++draft/range.sized) and `std::ranges::size` has one overload which uses iterators if it is a viable option (https://eel.is/c++draft/range.prim.size#2.5).
