### ISSUE TITLE
[BUG] In g++-10 seqan3::views::complement | seqan3::views::kmer_hash forward_range property is not preserved

### ISSUE THREAD

**Issue by MitraDarja** [seqan/seqan3#1963]
### Description 
Using `seqan3::views::complement | seqan3::views::kmer_hash` loses the forward_range property, it should preserve it though and with g++-version below 10 it does.

### How to repeat the problem

Compile with g++-10:
```c++
seqan3::dna5_vector text{"ACGTA"_dna5};
static_assert(std::ranges::forward_range<decltype(text | seqan3::views::complement | seqan3::views::kmer_hash(seqan3::ungapped{2}))>); // leads to a static assertion, which is not what we would expect
```

**Comment by eseiler** [comment]
Ok, I did a bit of digging (ping @marehr )

This compiles fine:

```cpp
seqan3::dna5_vector text{"ACGTA"_dna5};
using complement_view_t = decltype(text | seqan3::views::complement);
static_assert(std::ranges::bidirectional_range<complement_view_t>);
using it_t = std::ranges::iterator_t<complement_view_t>;
static_assert(std::same_as<typename std::iterator_traits<it_t>::iterator_category, std::input_iterator_tag>);
```

Somehow the complement view iterator is tagged as input iterator - which is then used in the kmer_hash_view.
This is the complement view:
https://github.com/seqan/seqan3/blob/095b5e12d9d3a7194356a7a34ce5215a19193ffe/include/seqan3/range/views/complement.hpp#L69

Basically it is just a transform view.
The standard says https://eel.is/c++draft/range.transform.iterator#2.1
```
2
iterator​::​iterator_­category is defined as follows: Let C denote the type iterator_­traits<iterator_­t<Base>>​::​iterator_­category.
(2.1) If is_­lvalue_­reference_­v<invoke_­result_­t<F&, range_­reference_­t<Base>>> is true, then
(2.1.1) if C models derived_­from<contiguous_­iterator_­tag>, iterator_­category denotes random_­access_­iterator_­tag;
(2.1.2) otherwise, iterator_­category denotes C.
(2.2) Otherwise, iterator_­category denotes input_­iterator_­tag.
```

We are (rightfully) in case 2.2. We can take a look at the lambda passed to the tranform view and check the condition:
```cpp
auto inner_lambda = [] (auto const & in)
{
    return seqan3::complement(in);
};

static_assert(std::is_lvalue_reference_v<std::invoke_result_t<decltype(inner_lambda)&, std::ranges::range_reference_t<decltype(text)>>>); // FAILS
```

We can look closer
```cpp
static_assert(std::same_as<std::invoke_result_t<decltype(inner_lambda)&, std::ranges::range_reference_t<decltype(text)>>, seqan3::dna5>); // OK
```

-> no lvalue reference!


I'm not sure how to handle this. Maybe we need to update the `iterator_tag_t` for cpp20 stuff (use `iterator_concept` if available, then use `iterator_category`, then deduce from concepts, or something similar) and use it in the kmer_hash_view instead of just accessing the iterator_category.

```cpp
using iterator_category = typename it_t::iterator_concept;
```
in the kmer_hash_view would fix this specific issue.

**Comment by marehr** [comment]
Thank you for deducting all of this.

You are right until your fix :)

Maybe some terminology before I start:

* `iterator_­category` indicates which kind of legacy iterator we have, a legacy input / forward / bidirectional / random-access iterator
* `iterator_­concept` indicates which kind of C++20 iterator we have, a C++20 input / forward / bidirectional / random-access / contiguous iterator

Because legacy iterators are fully valid C++20 iterators, we always can assign `iterator_­concept = iterator_­category`. The other way around is not true, because a C++20 input iterator for example, does not need to have a return type if you use the post-increment, i.e. `it++ -> void`.

```c++
using iterator_category = typename it_t::iterator_concept;
```
So doing that fix would be not right.

Your analysis was completely right that we are in case 2.2.

```
2
iterator​::​iterator_­category is defined as follows: Let C denote the type iterator_­traits<iterator_­t<Base>>​::​iterator_­category.
(2.1) If is_­lvalue_­reference_­v<invoke_­result_­t<F&, range_­reference_­t<Base>>> is true, then
(2.1.1) if C models derived_­from<contiguous_­iterator_­tag>, iterator_­category denotes random_­access_­iterator_­tag;
(2.1.2) otherwise, iterator_­category denotes C.
(2.2) Otherwise, iterator_­category denotes input_­iterator_­tag.
```

Why does the standard say here, that the `iterator_­category` must be a legacy `input_­iterator`?

This is quirk of the standard which required in it's named requirement for legacy `forward_iteratos`:

> The type std::iterator_traits<It>::reference must be exactly 
> * T& if It satisfies LegacyOutputIterator (It is mutable)
> * const T& otherwise (It is constant), 

So whatever the case, `*it` must be a lvalue of the value type. This was always bad, because this disallowed the use of proxy types within iterators. For example `std::bitset`, if it had an iterator, could only have a legacy input iterator, because you can't reference a single bit in c++.

The reference type of `seqan3::views::complement`, i.e. `std::ranges::range_reference_t<seqan3::views::complement>` is `dna5` in this case. Because, 

https://github.com/seqan/seqan3/blob/095b5e12d9d3a7194356a7a34ce5215a19193ffe/include/seqan3/range/views/complement.hpp#L69-L75

takes a `dna5 const` copy in and outputs a `dna5 const` copy. No lvalue, that means the iterator can't be a forward iterator.

---

The only right way would be to have a two type traits, one that gives you the legacy iterator tag back and one that gives you a C++20 iterator tag.

I'm currently working on a fix, and I would propose:

* `seqan3::detail::iterator_category_tag_t`, which is basically `seqan3::iterator_tag` and
* `seqan3::detail::iterator_concept_tag_t`, which is basically a huge conditional with if it is contiguous range => contiguous_iterator_tag, random access range => random_access_iterator_tag, and so on.
* `seqan3::detail::atmost_iterator_tag_t<tag, atmost_tag_t>` which does this "A contiguous range must downgrade to a random access range".

**Comment by eseiler** [comment]
> Thank you for deducting all of this.
> 
> You are right until your fix :)
> 

This was also the point where I didn't want to think anymore :)

> 
> The only way I see is to have two type traits, one that gives you the legacy iterator tag back and one that gives you a C++20 iterator tag.
> 
> I'm currently working on a fix, and I would propose:
> 
> * `seqan3::detail::iterator_category_tag_t`, which is basically `seqan3::iterator_tag` and returns you the legacy iterator tag and
> * `seqan3::detail::iterator_concept_tag_t`, which is basically a huge conditional with if it is contiguous range => contiguous_iterator_tag, random access range => random_access_iterator_tag, and so on.
> * `seqan3::detail::atmost_iterator_tag_t<tag, atmost_tag_t>` which does this "A contiguous range must downgrade to a random access range".

So we split `seqan3::iterator_tag` into two components? Or do we keep it and still have the two components.
`seqan3::iterator_tag`  returns the legacy iterator tag, if defined, and deduces it from the modelled range concepts otherwise.
But anyways, the fix sounds fine.

**Comment by marehr** [comment]
> So we split `seqan3::iterator_tag` into two components?

It's more like splitting, because it currently defines `_iterator`

**Comment by marehr** [comment]
A nice side effect: We found another defect in the standard library https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96070.

The not so nice side effect: My intended change does not work like I wanted.
