### ISSUE TITLE
Using cmake 3.14 options but cmake require only 3.7

### ISSUE THREAD

**Issue by lhovo** [seqan/seqan3#2227]
## Platform

  - SeqAn version: 3.0.2
  - Operating system: Linux 4.14.193-149.317.amzn2.x86_64 #1 SMP Thu Sep 3 19:04:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  - Compiler: cpp (GCC) 7.3.1 20180712 (Red Hat 7.3.1-9)

## Description
The cmake file
`build_system/seqan3-install.cmake`
has
`cmake_minimum_required (VERSION 3.7)`

Though it also is using version 3.14 Features
```
install (
    FILES
    ...
    TYPE DOC
)
```
If cmake 3.14 features are being used then the cmake_minimum_required should be updated

### How to repeat the problem
Have cmake version 3.13 or below installed

### Expected behaviour
Install to work

### Actual behaviour
Error as install has no Destination

**Comment by sagitter** [comment]
[EPEL](https://fedoraproject.org/wiki/EPEL)-7 repositories provide the `cmake3-3.17.3` RPM if can be useful.

**Comment by lhovo** [comment]
Thanks, I have compiled the latest and it is working now.
It would have been nice to know the version was an issue (with the check being correct) vs debugging the script and why it was failing

**Comment by lhovo** [comment]
I have pushed up a PR to fix this
https://github.com/seqan/seqan3/pull/2228

**Comment by marehr** [comment]
Thank you :)

One extra question: Did you even need to install it, or were you only using the top-level cmake and it gave you this error by default?

Can you give us the exact way you executed the cmake file? (e.g. `cmake <src>`, in cmake via `add_subdirectory`, or `ExternalProject`)

If you had specified `cmake -DINSTALL_SEQAN3=OFF <seqan3-src>` this error shouldn't have triggered, because without the installation target we would have been fine with `cmake 3.4`.

I'm thinking to set the (currently) always enabled `INSTALL_SEQAN3` option depending on whether the cmake version is at least `3.14`.

**Comment by lhovo** [comment]
Yes I was using the top-level `CMakeLists.txt` to fit in with the larger project and install the includes in the one directory
```
git clone https://github.com/seqan/seqan3.git --depth=1 --branch=3.0.2 --recurse-submodules
cd seqan3; mkdir build; cd build
cmake .. -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=OFF \
  -DCMAKE_INSTALL_PREFIX=${PWD}../../include \
  -DCMAKE_PREFIX_PATH=${PWD}../../include
make install
```

**Comment by marehr** [comment]
Okay thank you! That means we have to document that we only support `make install` for `cmake >= 3.14` and that you can enable/disable `make install` by specifying `cmake -DINSTALL_SEQAN3=ON/OFF <seqan3_src>`.

I think we haven't documented that usage in our user documentation, yet. Are you using cmake in your project? Or are you using a different build system?
