### ISSUE TITLE
Pairwise (local) Alignment with Minimum Length

### ISSUE THREAD

**Issue by jjhuy-wq** [seqan/seqan3#2362]
## Platform

  - SeqAn version: 3.0.2
  - Operating system: macOS 11.1
  - Compiler: g++-9 (Homebrew GCC 9.3.0) 9.3.0
## Question

Is there a way to set a minimum length of the local alignment?
For example, I always get alignments with super short sequences, e.g.:
```
seq1: GGTCTGTAATGAGTGGGCAGGCGGTGAGCAGTCGTTTCTTCGTTCGAAGAAGGACAATGGCAAGCTGAACGTACACAATCCGGACGGCGGTCGCAAGTTAGACTCGGTACTAGTTTGAGAAGTTAAGCTAGTAACAGGGT
seq2: GAGATCGGAA
GAGATCGGAA
Score: 2
Begin: (7,6)
End: (9,8)
```

```c++
 // Configure the output:
auto output_config = seqan3::align_cfg::output_score{} |
     seqan3::align_cfg::output_begin_position{} |
     seqan3::align_cfg::output_end_position{} |
     seqan3::align_cfg::output_alignment{};

seqan3::nucleotide_scoring_scheme scheme; // hamming distance is default

 // Configure the alignment kernel.
auto config = seqan3::align_cfg::method_local{} |
    seqan3::align_cfg::scoring_scheme{scheme} | output_config;

auto results = seqan3::align_pairwise(p, config);
```

Thanks

**Comment by marehr** [comment]
Hi @jjhuy-wq,

thank you for asking, I'll double-check your question with the main-author of the alignment module. This post is more like a collection of thoughts to understand what you mean.

This is quite an interesting question, because from my perspective these are the most-common use cases:
 
* enumerate all positions that have the same best score, (not-implemented yet)
* enumerate one alignment that has a score of at least some score, ([seqan3::align_cfg::min_score](https://docs.seqan.de/seqan/3-master-user/classseqan3_1_1align__cfg_1_1min__score.html))
* enumerate all sub-optimal alignments (i.e. sorted by score) (not-implemented yet)

So typical use cases would be to optimize for score. From that perspective it would be fine to skip all scores that don't match that minimal sequence criteria.

You on the other hand want a different optimization, you want the best score which has at least some length. Hmm, what does that even mean? Let's say I have a read-sequence of length 5. If I say my resulting sequence must be at least 3. This would exclude sequence of length 1 and 2, but would consider sequences of length 3, 4 and 5. Local-Alignments are peculiar, because they can "restart" their score. So they can deem a sub-sequence of length 2 as optimal, but that sub-sequence extended by one char as a failure and start-over. That means only longer chains within the trace-matrix can be considered, but any shorter sub-chain might not have the optimal score for that sequence length. So in short: any sub-sequence of the optimal sub-sequence might not be optimal in itself.

This seems like one could modify the dynamic program's optimization criteria to satisfy this extra constraint.

Some questions:
* Can you specify what lengths you would expect? Maybe you can use semi-global alignments?
* Do you know of a different tool / library that offers that? That would make it easier to "inspire" us :)
* I found this paper https://www.researchgate.net/publication/225666409_Algorithms_for_Local_Alignment_with_Length_Constraints which seems promising, I haven't read it yet. But maybe it gives you some inspiration.

**Comment by marehr** [comment]
I'm still wondering how you would interpret the result. If you get "short" sub-sequence out of your local-alignment, that means (for a normal scoring scheme with +score for match, -score for mismatch) that you have no longer (in the sense of length) "similar" sub-sequences that are more similar than your optimal one. So enforcing a minimal length will result in a pretty bad alignment, because any longer would have a negative effect on the "similarity". In general the scoring matrix should produce the longest "matching" sequence.

Can't you just skip such a bad alignment?

**Comment by jjhuy-wq** [comment]
Hello @marehr,
thank you for answering. I think you are right. Thought about it wrong. Cutting down the length would only make sense if the sub-optimal alignments would also be reported and then I could filter the alignments accordingly. Would be interested in this feature. For now, I think I will neglect alignments that fall below this length. Thank you for the references, I will have a look at it. In principle, I want to calculate a complementarity score by using local alignments with an alternate scoring. And to have a comparison between the reads I want to have a minimum length... just to filter out really short ones < 10. 

However, I think the main problem is that I somehow don't get the local alignment to work. For example, I'm using the following minimal example:
```

#include <vector>
#include <seqan3/alignment/configuration/align_config_edit.hpp>
#include <seqan3/alignment/pairwise/align_pairwise.hpp>
#include <seqan3/alphabet/nucleotide/dna5.hpp>
#include <seqan3/core/debug_stream.hpp>

int main() {
    using seqan3::operator""_dna5;

    auto output_config = seqan3::align_cfg::output_score{} | seqan3::align_cfg::output_begin_position{} |
        seqan3::align_cfg::output_end_position{} | seqan3::align_cfg::output_alignment{};
    auto config = seqan3::align_cfg::method_local{} |  seqan3::align_cfg::scoring_scheme{seqan3::nucleotide_scoring_scheme{}} | output_config;

    std::vector vec{"GTTGCTTCTC"_dna5, "ATCGAAATCCGGAAAAGTTGCTTCTCTCAAGGCTGAGG"_dna5};

    auto result = seqan3::align_pairwise(std::tie(vec[0], vec[1]), config);
    auto & res = *result.begin();


    seqan3::debug_stream << "seq 1: " << vec[0] << '\n';
    seqan3::debug_stream << "seq 2: " << vec[1] << '\n';
    seqan3::debug_stream << "Score: " << res.score() << '\n';
    seqan3::debug_stream << "Begin: (" << res.sequence1_begin_position() << "," << res.sequence2_begin_position() << ")\n";
    seqan3::debug_stream << "End: (" << res.sequence1_end_position() << "," << res.sequence2_end_position() << ")\n";

}
```
Although, seq1 is a substring of seq2 I still get a score of 0.
```
seq 1: GTTGCTTCTC
seq 2: ATCGAAATCCGGAAAAGTTGCTTCTCTCAAGGCTGAGG
Score: 0
Begin: (0,0)
End: (0,0)
```
What am I doing wrong? Thanks again.

**Comment by marehr** [comment]
Hi @jjhuy-wq,

I'm terribly sorry for answering so late.

The main problem that your scoring-scheme is (match: 0, mismatch: -1) and gap-costs are (gap open cost: 0,  gap extension cost: -1), that means edit distance.

You are basically saying only penalise mismatches and gaps, but don't incentivise matches.

That means your alignment score can ONLY be negative or zero, but the local alignment algorithm will always keep the score positive. So a local alignment with hamming distance can only produce an optimal score of 0.

That means edit distance (and hamming distance) makes only sense for (semi-)global alignments.

If you change the scoring scheme to (match: 1, mismatch: -1, gap extension cost: -1):

```c++
    auto method = seqan3::align_cfg::method_local{};
    seqan3::align_cfg::scoring_scheme scheme{seqan3::nucleotide_scoring_scheme{seqan3::match_score{1}, seqan3::mismatch_score{-1}}};
    seqan3::align_cfg::gap_cost_affine gap_costs{seqan3::align_cfg::open_score{0}, seqan3::align_cfg::extension_score{-1}};
    auto config = method | scheme | gap_costs | output_config;
```

You'll get 

```
seq 1: GGTCTGTAATGAGTGGGCAGGCGGTGAGCAGTCGTTTCTTCGTTCGAAGAAGGACAATGGCAAGCTGAACGTACACAATCCGGACGGCGGTCGCAAGTTAGACTCGGTACTAGTTTGAGAAGTTAAGCTAGTAACAGGGT
seq 2: GAGATCGGAA
Score: 6
Begin: (99,1)
End: (107,8)
Alignment: ((AGACTCGG,AGA-TCGG))
```

**Comment by marehr** [comment]
Hi @jjhuy-wq, we close this issue, because we think that we resolved the question. If you have any further questions or remarks, please re-open the issue.
