### ISSUE TITLE
metafunction → type_traits

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#243]
We should switch the vocabulary of the standard also for metafunctions, this means:

- [ ] Use new names:
  * "value metafunction" → TypeTrait
  * "type metafunction" → TransformationTrait
- [ ] update API documentation
- [ ] formally introduce concepts unary_type_trait_concept and binary_type_trait_concept fpr TypeTraits and transformation_trait_concept for TransformationTrait; TypeTraits shall inherit std::integral_constant
- [ ] change "metafunction" wiki article to "Type traits, traits-types and metafunctions" and explain all

**Comment by marehr** [comment]
I don't understand this. Can you give an example?

**Comment by rrahn** [comment]
I think he refers to the naming of such constructs.
But honestly, at least cppreference uses a wide range of categories for the type support.
So where exactly are the definitions above described formally?

**Comment by h-2** [comment]
> So where exactly are the definitions above described formally?

Sure:
https://en.cppreference.com/w/cpp/concept/UnaryTypeTrait
https://en.cppreference.com/w/cpp/concept/TransformationTrait

**Comment by rrahn** [comment]
cool. Thanks for the pointer.

**Comment by marehr** [comment]
okay, cool, so that means:

* a meta function is a type_trait if it inherits from `integral_constant` for every possible template parameter. Even though the name is integral_constant, it could have as value_type floats, enums, function_pointers, etc... So basically every function that has a `_v` helper.
  
  Except for the following meta function that are *NOT* type_traits ...
  * ... that is only partially defined
  * ... where SFINAE would fail
  * ... hat behaves like a `intergral_constant`, i.e. if it's self written

**Comment by rrahn** [comment]
This is something fundamental we need do tackle before the release.
