### ISSUE TITLE
Finalise the search interface design

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#260]
Both for SA-like indexes and hash tables.

**Comment by cpockrandt** [comment]
Current draft:

* max_error(int)
* min_error(int)
* max_error_rate(float) // this will simplify searching a set of reads of different lengths
* min_error_rate(float)
* allow_duplicates // faster mode with no filtration (for indels and variable_length_seeding) and mismatches for <= 5 errors (where no (disjunct) search scheme is defined)
* compute_alignment
* distance_metric(hamming) // or edit-distance (shortcut for error_types)
* error_types(substitutions | insertions | deletions) // any combination of these tags
* output_format(text_pos) // alternative: iterator (of type index_type::iterator) or explicitely a unidirectional_iterator (fwd or rev strand)
* variable_length_seeding(int max_hits, int offset = 1, min_length = 0) // works with errors, distances, etc.
* > [] on_hit(iterator/text_pos, const & read, const & id (?), alignment-object, errors/error_rate) {...}

Open questions/discussions?

1. separate count-interface? similar interface like `search` (without allow_duplicates und output_format) with a different delegate-function and return type of ranges:

    > [] on_hit(const & read, const & id (?), unsigned hits) {...}

    or a range for integers (one dimension less than `search`)

2. how to pass read_id to delegate? how should the input look like? tuples? and what would be an efficient implementation for a range-result (no referenes?)

3. Maybe introduce some optimization_tags such as `all_reads_same_length` that speed up the search algorithms? needs some benchmarking first ...

future work that is postponed:
- parallelization tags
- output alignment
- handle support for searching different alphabets: iupac/dna murphy10/protein, etc.

**Comment by eseiler** [comment]
Do we want to add all/best hits and strata here or somewhere else?

**Comment by cpockrandt** [comment]
@eseiler: Here's an update that I started implementing in #292 

Major changes:

1. no min_error, no distance_metric alias, no filter_duplicates (duplicates will be always filtered)
2. separate cfg objects `substitution`, `insertion`, `deletion` instead of `error_types(substitution | insertion | deletion)` to make the input constexpr without the hack `error_types(as_c<substitution | insertion | deletion>)`. If we make it a runtime decision we would have 2^3 code paths.

Config objects:
* max_error(int) or max_error_rate(double)
* substitution and/or insertion and/or deletion (see question 2)
* output_text_position or output_iterator (see question 1)
* all, best, all_best or strata(int)
* on_hit([...](iterator/text_pos, query_id, query_pos, errors/error_rate) {})

Questions:

1. Do we want a configuration `output_iterator` if it is set by default anyway? (@rrahn)
2. Replace flags like `substitution` by `substitution_max_error(int)` and `substitution_max_error_rate(double)` to allow different number of errors for different error types. `max_error(int)` and `max_error_rate(int)` could remain to set an upper bound of errors since it could happen that `substitution_max_error + insertion_max_error + deletion_max_error > max_error`.

**Comment by rrahn** [comment]
@eseiler @cpockrandt what is the status here?

**Comment by h-2** [comment]
All things discussed here are done, I think, but we have started a new discussion on the indexes...
