### ISSUE TITLE
revisit declare_view_functor_type

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#272]
During PR #270, we started to discuss some implementation details that (may) should be done differently.

- [x] Use this declaration?
  ```cpp
  template <template <typename, typename ...> class view_type>
  struct declare_view_functor_type
  {
  ...
  };
  ```
- [ ] #221: Should this syntax be allowed? 
  ```cpp
  auto v = std::vector<int>{0, 1, 2, 3} | my_view(); 
  ```

- [x] The following assumes [class template argument deduction](http://en.cppreference.com/w/cpp/language/class_template_argument_deduction)

  https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/detail.hpp#L142-L149

- [x] Should be DRYed?

  https://github.com/seqan/seqan3/blob/3ec70140d53880409762ef71f46485d73a235aa0/include/seqan3/range/view/detail.hpp#L322-L328

  to

  ```c++
    template <typename urng_t>
    friend auto operator|(urng_t && urange,
                          [[maybe_unused]] declare_view_functor_type const & fn)
        requires requires { view_type{std::declval<urng_t>()}; }
    {
        return fn(std::forward<urng_t>(urange));
    }
  ```

**Comment by marehr** [comment]
h-2 wrote in https://github.com/seqan/seqan3/pull/270#issuecomment-395221865:

> I still use the functor for DRY reasons

That was my reason, as well. It is good to have one point where you delegate to the type and not multiple.

> Second, I think the functor should be declared as:
>
> ```cpp
> template <template <typename, typename ...> class view_type>
> struct declare_view_functor_type
> {
> ...
> };
> ```
> since we don't know, if the underlying view might need multiple template parameters.

IIRC I had this at some point, but something didn't work. I think it is because `view_type` is actually not fully deduced and the functions would need to the second parameter pack, but they don't have it's name. This would only work if the template parameters where passed the functor explicitly (I remember having that, but it is more ugly).
[it works here without template arguments only because it relies on argument deduction guides in view_type]

In any case I can have a look at it again when I am back, but this is not related to the issue.

**Comment by rrahn** [comment]
To add my opinion to the discussion points:

1. I think this is more correct, and probably need to be added at some time as number of our own view implementations grow. At the moment I' couldn't see how this defeats the simplicity of the functor usage as I don't think one needs to pass the template arguments to the function call operators. But if a counter exampled proves otherwise, we need to reconsider and possibly restrict the view implementations to a single template argument.

1.  IMHO, this will also not be supported by the STL. Again, we are adding, possibly stateful, filters/algorithms to an underlying range not a class or instance of something that owns data. So if there is no redesign of the range TS in the STL of C++20, then I guess we need to acquaint to the proposed style, which means #221 is not an issue but a design decision.

1. At least the `view_type` needs to have the fitting constructor, so adding template deduction shouldn't be a problem. I think views should not be that complex.

1. If possible DRY it and if not, I think this functor type is very self-contained and might not suffer from possible repetitions.

**Comment by h-2** [comment]
1. and 4. addressed with #280 

2. I am not sure if we should support it, in any case it's not a priority

3. is correct

**Comment by rrahn** [comment]
with the #420 we have awnsered 2.
So I close this ticket.

**Comment by h-2** [comment]
There are still open issues with the adaptor, but I will open something separate for them.

**Comment by rrahn** [comment]
I think there is another ticket for this.
