### ISSUE TITLE
Always use std::error_code for exceptions...

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#273]
... and catch exceptions via value instead of reference.

BECAUSE it will enable us to upgrade to [Zero-overhead deterministic exceptions](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0709r0.pdf) once they are merged (which seems likely for C++20). We could just upgrade to this mechanism with a macro in this form

```cpp
#if __has_feature(...)
#define SEQAN3_THROWS throws
#else
#define SEQAN3_THROWS
#endif
```

**Comment by smehringer** [comment]
Closing this in favour of a card In the Seqan4 project

**Comment by rrahn** [comment]
> Closing this in favour of a card In the Seqan4 project? 

Who decided this? I am still in favor of switching to using std::error_codes instead of plain exceptions. Especially for the argument parser, the I/O and I am already planning it for the alignment. I guess Search can benefit from it as well. This has nothing to do with the referenced proposal. But it kind of is an open ticket in my icebox.

**Comment by smehringer** [comment]
Huh? I was pretty sure we decided to keep all proposals as cards in the projects unless we decide to work on them in the current release (as a way to reduce the number of open and stale issues).

**Comment by rrahn** [comment]
Well, I agree in general, but I quite often said that I am working on a good way to manage the product backlog. So while I am trying out different arrangements of the things so that I am happy and everyone else has not to bother with another managing system (because that's what everyone decided), it gets a little disruptive for me when things vanish out of my control flow. Note, at the moment, due to limited time resources, I am in general in favor of sharing the orchestration of tickets/cards within the team, but then we should have a meeting and discuss these together. Especially, since this is not a SeqAn4 issue. However, in the future I'd like to bring it to a more structured system in order to avoid conflicts and improve the general workflow. Especially, to discuss and present the tickets more effectively once we have the monitor.
