### ISSUE TITLE
What is the size of a dnaX_vector?

### ISSUE THREAD

**Issue by JanSiebert** [seqan/seqan3#2924]
## Question

I am wondering about the size of a `dna5_vector`. I've found that it is an alias for `std::vector<dna5>` and `dna5` itself occupies one byte (`uint8_t`). 

**Does `dnaX_vector` allocate at least 1 byte per nucleotide, or is there a bitvector-like optimization?**

Thank you!

**Comment by smehringer** [comment]
Hi @JanSiebert,

thanks for your interest in SeqAn!

> Does dnaX_vector allocate at least 1 byte per nucleotide [...]?

Yes. Since the `dnaX::rank_type` is at least `uint8_t` (alphabets are stored as their ranks in `seqan3`), they occupy at least one byte.

> [...] or is there a bitvector-like optimization?

Yes there is. We have the `seqan3::bitpacked_sequence` see [here](http://docs.seqan.de/seqan/3-master-dev/classseqan3_1_1bitpacked__sequence.html#details).

Example:
```cpp
#include <vector>
 
#include <seqan3/alphabet/container/bitpacked_sequence.hpp>
#include <seqan3/alphabet/nucleotide/dna4.hpp>
 
int main()
{
    using namespace seqan3::literals;
 
    std::vector<seqan3::dna4> v0{"ACGT"_dna4}; // data occupies 4 bytes in memory
    seqan3::bitpacked_sequence<seqan3::dna4> v1{"ACGT"_dna4}; // data occupies 1 byte in memory
}
```

**Comment by smehringer** [comment]
Hi @JanSiebert,

this question seems resolved to me. Feel free to reopen the issue if something is missing for you.
