### ISSUE TITLE
IBF space overhead

### ISSUE THREAD

**Issue by JensUweUlrich** [seqan/seqan3#2940]
### Does this problem persist on the current master?

- [X] I have verified the issue on the current master

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the interleaved Bloom filter, I created 10 bins with 10,000,000 entries and 3 hash functions. I calculated the binsize such that the FPR would be at around 0.01. This results in an IBF size of 943 MB, which is much bigger than I would expect based on the Bloom Filter calculator (https://hur.st/bloomfilter/?n=10000000&p=0.01&m=&k=3). Using only 1 bin will give me an IBF size of 943 MB as well (Expected size should be about 14.7 MB). It seems that the usage of technical bins results in such a big overhead. I wonder whether this is a bug or not. It seems to be related to the usage of technical bins.

### Expected Behavior

I would expect the IBF to use much less space.

### Steps To Reproduce

Use the following code snippet to reproduce the issue:

```
inline uint64_t get_bin_size( double false_positive, uint16_t hash_functions, uint64_t max_hashes )
{
    return std::ceil( max_hashes
                      * ( -hash_functions / std::log( 1 - std::exp( std::log( false_positive ) / hash_functions ) ) ) );
}

size_t nr_elems = 10000000;
for (int e = 0; e < 1 ; ++e)
{
	std::vector<uint64_t> tmp{};
	for (uint64_t i = 0; i < nr_elems; ++i)
	{
		uint64_t key = (e*nr_elems) + i;
		tmp.emplace_back(key);
	}
	elems.emplace_back(std::move(tmp));
}

uint64_t BinSizeBits = get_bin_size(0.01, 3, nr_elems);
std::cout << "Size of 1 Bin in MByte: " << (double) BinSizeBits / (double) 8388608 << std::endl;
seqan3::interleaved_bloom_filter ibf{seqan3::bin_count{1u}, seqan3::bin_size{BinSizeBits}, seqan3::hash_function_count{3u}};
for (uint16_t i = 0; i < elems.size(); ++i)
{
	for (uint64_t key : elems[i])
		ibf.emplace(key, seqan3::bin_index{i});
}

mbytes = (double) ibf.bit_size() / (double) 8388608;
std::cout << "Size of the IBF: " << mbytes << " MBytes" << std::endl;
```

### Environment

```markdown
- Operating system: Ubuntu 20.04
- SeqAn version: 3.1.0 
- Compiler: gcc 9.4.0
```

**Comment by eseiler** [comment]
Yes, you will always allocate space for the next multiple of 64. So, if you have 10 bins, you will still allocate for 64. 

You could either [compress the IBF](https://docs.seqan.de/seqan/3-master-user/classseqan3_1_1interleaved__bloom__filter.html#ae33f5a999f37570f33044174bc834576), or split your sequences into 64 instead of 10 bins.

**Comment by smehringer** [comment]
Hi @JensUweUlrich,

as @eseiler said this is expected because our smallest unit is a machine word with 64 bits.

Do you have an actual use case with such a low number of user bins or is this just for testing purposes? 

If the former is the case, we have developed an algorithm that splits user user bins s.t. the IBF size is reduced but it's currently an application that only works with the application raptor and its not part of seqan3 yet.
