### ISSUE TITLE
[IO] Typedef for numeric reference ID type, constant for invalid reference ID in SAM/BAM input

### ISSUE THREAD

**Issue by tsnorri** [seqan/seqan3#3084]
Consider the use case where SAM records are handled by the value of the RNAME field. Since SeqAn maps the RNAMEs to numeric identifiers, checking whether consecutive records have the same reference sequence is quite easy. To this end, one typically would write code like the following:

```c++
some_type prev_ref_id{SOME_CONSTANT}; // Initially set to an unused value.
for (auto const &aln_rec : alignment_records)
{
    auto const ref_id_(aln_rec.reference_id());
    if (!ref_id_.has_value())
        continue;

    if (prev_ref_id != *ref_id)
    {
        // Do some preprocessing.
    }

    // ...
}
```

Currently `some_type` is defined to `std::int32_t` in `sam_file_header`, but there is no easily accessible typedef. Since the value is used as a deque index, any negative values would presumably be unused, but a named constant would be nice.

(I would have made a pull request instead but wasn’t sure if the values should be defined in `sam_record`, `sam_file_input` or somewhere else.)

**Comment by smehringer** [comment]
Hi @tsnorri,

thanks for reaching out!

If I understand correctly, and please correct me if I'm wrong, you'd like

#### 1. An accessible typedef for the type `some_type` in your example.
   
We might already have that: The `sam_file_input` sotres the member type `ref_id_type`.

Sorry for the naming inconsistencies, unfortunately we are still working on the IO. and it's not stable yet.
Could be that this already serves your needs:
```cpp
seqan3::sam_file_input fin{"test.sam"};
using ref_id_type = typename decltype(fin)::ref_id_type; // std::option<int32_t>
using some_type = typename decltype(fin)::ref_id_type::value_type; // int32_t
```

#### 2. A named constant of type `int32_t` for ivalid reference IDs

S.t. you could for example do 
```
aln_rec.reference_id().value() == seqan3::sam_file::invalid_reference_id
```
?

This would be orthogonal to the approach we chose with the `std::optional<int32_t>` since you can check invalid ids, as you did, with `aln_rec.reference_id().has_value()`

We might revise this choice. I agree that a named constant is helpful. It would make using a `std::optional<int32_t>` obsolete and we could use a `int32_t` directly, decreasing complexity.

**Comment by tsnorri** [comment]
Thank you for the quick reply and pointing out `ref_id_type`. I should have noticed it as it is documented but the function declarations `decltype(auto) reference_id()` in `sam_record` misled me a bit. Using `std::optional` the way you described makes sense, so it is quite the same to me which approach you choose.
