### ISSUE TITLE
Try doxypress for documentation

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#375]
https://github.com/copperspice/doxypress is a fork of Doxygen that supposedly supports modern C++ better. Someone should check it out, it might be as easy, as installing, converting our config and running it on our codebase.

**Comment by eseiler** [comment]
I tried it for a bit and had some problems:

They have a command line version and a GUI version:
- The GUI version can be used (also via the command line) to convert the file from doxygen to doxypress, but requires an X-Server
- The command line version **cannot** convert

Even if I convert it via the GUI and then try to generate the docs:
- it gets stuck for some files while parsing ( e.g., `alphabet/composition/cartesian_composition.hpp`, `core/algorithm/configuration.hpp` and `std/concept/core_language.hpp`), so you need to exclude them
- with excluded files it parses and generates 107 warnings and terminates with
```
Generating docs for namespace compounds seqan3::alphabet_concept
terminate called after throwing an instance of 'std::logic_error'
  what():  QList<T>::operator[] Index is out of Range. (Index is 5, Size is 2)
Aborted
```

I used the precompiled binaries, because building needs GUI libraries...

But, there is now a clang version which supports concepts ([Reddit post](https://www.reddit.com/r/cpp/comments/958sj9/clang_concepts_is_now_featurecomplete/) and [git repo](https://github.com/saarraz/clang-concepts))
While both llvm and clang need to be build, it would be interesting to at least keep an eye on it and maybe try it out and look what doxygen says to the output?

**Comment by rrahn** [comment]
Ok let's revisti it when we have stable clang support.
