### ISSUE TITLE
[Argument Parser] empty argument list on input causes short help printing instead of warning about missing required options

### ISSUE THREAD

**Issue by dombrowsky** [seqan/seqan3#491]
If parser options are required but non specified, the program should fail with the specified error:

```c++
#include <seqan3/io/stream/debug_stream.hpp>
#include <seqan3/io/sequence_file/input.hpp>
#include <seqan3/argument_parser/all.hpp>

using namespace seqan3;

int main(int argc, char const ** argv)
{
    seqan3::argument_parser p("foo", argc, argv);
    std::string input{"input.file"};
    p.add_option(input,'i',"--input","Input file",seqan3::option_spec::REQUIRED);
        try
    {
        p.parse();
    }
    catch(seqan3::parser_invalid_argument const & ext)
    {
        // should throw invalid parser when invoked like "> foo "
        std::cerr << "[PARSER ERROR]: " << ext.what() << std::endl;
        return 1;
    }
    catch(seqan3::parser_interruption const &)
    {
        return 0;
    }
}
```

**Comment by eseiler** [comment]
Hey @dombrowsky,

thanks for your input!

If no arguments are at all provided to the program, the argument parser considers this as a `parser_interruption` and prints a short usage message (if provided) and a hint for using `-h, --help`.
Usually this is the expected behaviour when calling a program without any arguments.
@smehringer may know more about why it is the way it is.

If you use call `foo bar` it will throw the expected error, even though the `bar` argument is also invalid.
Calling `foo bar -i input` will throw an en exception for the unexpected bar option.

**Comment by smehringer** [comment]
Thanks for reporting this here @dombrowsky.

As @eseiler said, this behaviour is intended by us right now, because we decided that usually a `./program` call is not intended to start the program but used by people that do not know which arguments to supply and are thus redirected to the help page for further information. We will discuss with the Team whether we change this when required options are specified.

**Comment by rrahn** [comment]
@dombrowsky If the program is called without any arguments it prints the synopsis/help of the tool. I think this is the expected behavior. If you think that there are valid reasons not to then please reopen this issue.
