### ISSUE TITLE
constexpr on east or west side

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#592]
Examples:

* variables 
  ```c++
   static size_t constexpr value_size = size;
  ```
  or
  ```c++
   static constexpr size_t value_size = size;
  ```

* functions 
  ```c++
   friend bool constexpr operator==(derived_type const & lhs, derived_type const & rhs) noexcept
  ```
  or
  ```c++
   friend constexpr bool operator==(derived_type const & lhs, derived_type const & rhs) noexcept
  ```

**Comment by smehringer** [comment]
I so do not care. Let's decide quickly, add a note in the wiki and close this issue again.

**Comment by h-2** [comment]
> variables
> functions

For variables the `constexpr` implies `const` so if we omit the `const` we should put the `constexpr` where the `const` is. 

For functions the `constexpr` does not imply `const`, in fact it doesn't change the return type at all, it only signifies that the function can be called in a `constexpr` context. So for functions we don't need to put it east and in fact it might make more sense to put it where we otherwise put `inline`, i.e. west, because it implies `inline`.

> I really do not care. Let's decide quickly, add a note in the wiki and close this issue again.

There has been documentation on this in the wiki since almost three months.
https://github.com/seqan/seqan3/wiki/General-formatting

**Comment by smehringer** [comment]
I see that this is important more important than I thought. Please let's not discuss this further for now but I'll schedule this for the DEV meeting at the :date: 11th of December (h-2 is not here next week) so we can think this through before changing anything.
As this will only be a refactoring, ongoing PR's shall follow the wiki guidelines for now and will be refactored once this is decided.
