### ISSUE TITLE
union_composition clean-up: documentation

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#68]
This is a detail/discussion ticket of the meta ticket #60 

 * [x] add `\param` documentation to all functions
 * [x] don't use `namespace seqan3::detail::union_alphabet` since it doesn't appear in doxygen
 * [x] don't use `\privatesection` and `\publicsection` outside of class scope (it doesn't have any effect there)
 * [x] add `\ingroup composition` where needed!

**Comment by marehr** [comment]
@h-2 I think we should always scope our privately used functions in a separate detail namespace, like `namespace seqan3::detail::union_alphabet`

For example: I think you used at some point a function `detail::create_value_to_char` to generate the conversion tables of nucleotides. This function name was kind of ambiguous, because it only applied for nucleotide, but nearly all our alphabet types (also aminoacids) have a `value_to_char` conversion table.

For the `union_alphabet` I named the function `detail::union_alphabet::value_to_char_table`, which makes it much more understandable, that THIS private helper function only belongs to the `union_alphabet` class.

Had I named my function also `detail::create_value_to_char`, we would had a name clash, that we might not have catched, because our `#include`s might not weave together and thus only a user would have catched that.

I think we should only put functions into `seqan3::detail` if it is relevant for a lot of classes/

**Comment by h-2** [comment]
@marehr @rrahn 
This is an important decision that we should maybe discuss in person. But for the record here are my thoughts on this. 
In the beginning I had the same notions as @marehr  which is why the wiki also states:

> if you write lot's of code that is specific to a module or file and may collide with other implementations, you can create sub-namespaces under `detail`

But I have come to regret this. For the following reasons:
  * every namespace has to be individually documented, or none of its contents will display in the doc
  * this creates extra documentation overhead and extra room for mistakes, e.g. does `seqan3::detail::convert` belong to `view::convert` ? Should it then not be `seqan3::view::detail::convert` or `seqan3::detail::view::convert`? Will the sub-namespace be the filename, or the class name, or the concept name...?
  * you can immediately access the members of the current namespace, and the one above, but not higher up, i.e. inside `seqan3::detail` you can access things from `seqan3`, but from `seqan3::detail::foobar` you can no longer access `seqan3` implicitly
  * **over-specialization: ** We already have multiple angles of browsing our documentation, either through a file-tree, or through the module-tree. #54 will already bring these closer together which is really good. In contrast the namespace angle to our source code is orthogonal to this and luckily it is very flat, i.e. we have `seqan3` and `::view` and `::action` and for devs also `::detail` (I am in favor of merging `::literals` into `seqan3`); if we start sub-branching on these, it will just make it more confusing, because there will be multiple layers "encapsulation" that in part contradict each other.

I see the arguments raised in favor of this, but I think we can solve it quite easily in the following manner:
  * If some non-member function belongs to class, it shall be a `private static` function of that class. Really this makes a lot of sense when you think about it and it provides exactly the behaviour that we want in regards to encapsulation, namespaces and doxygen.
  * If some non-member function belongs to a concept, it shall have `\relates CONCEPTNAME` in it's doxygen. This will mark it clearly for the person reading the source code *and* the documentation as belonging to that concept. In addition we already also have the `\ingroup MODULENAME` information, but again, this is in accordance to the already existing hierarchy of types and modules, and is not an additional layer of inheritance and subdivision...
  * The same can be done for meta-functions, both type and value.

**Comment by rrahn** [comment]
In general, I think we should not *overuse* namespaces and keep it to a minimum (like as is right now). 
It will always be possible to accidentally repeat an already existing symbol. So we need a test that includes everything and also tests for multiple translation units, as we have with seqan2 to detect this.

Anyway, the common practice is to stay close to the class implementation. So if you have some meta-function voodoo for your class it can be added as a static private member function. Later if someone else needs the same for some other class, it can be refactored and added as a global meta function or maybe inherited from some meta-mixin class, which can be implemented in the ```detail::``` namespace. 

If you can implement a function as a non-friend non-member function, do it (e.g. find()). Otherwise the function is a member-function (or non-member friend) and the scope is clear. 
If the function does not belong to the API, it shall be a *protected/private* member-function. But prefer protected over private, unless there is a really good reason for it.

So the ```value_to_char``` conversion is clearly dependent on the members of the class and does not belong to the API. Hence it should be a protected function of that class. If the same functionality can be reused between different alphabet types, we could then have a  utility conversion function in ```detail::``` as part of a mixin inherited by the target classes or as a free-meta function but constrained by a concept/type to be applied for. 
In general, all free-functions must be constrained (please prove me wrong, if I am not seeing something here). So there is no need for extra namespace voodoo.
Apart from that, the doxygen problem seems to be solved with this as well, according to @h-2.
