### ISSUE TITLE
add view::interleave

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#706]
`"ABCDE" | view::interleave(2, "#")`
-> `"AB#CD#E"`

We are using this in multiple places and I expect a custom view to be much more efficient than `view::chunk(2) | view::join("#") `
because view::join is just so bad. Also we could preserve random access and size!!!

**Comment by smehringer** [comment]
@h-2 Can you give more details so @joshuak94 can work on this?

**Comment by h-2** [comment]
@joshuak94 This is similar to the single_pass_view you worked on, i.e. it should inherit from the view_interface.

Constructors take three parameters instead of one:
  1. the underlying range
  2. step size (`size_t`)
  3. inserted_range (templatised parameter, some RandomAccessRange+SizedRage over the same value_type as the underlying range)

It can use our detail::random_access_iterator as an iterator. The main members that you need to define are
  * `size()`
  * `operator[]`

In the above example `size()` of the underlying range is 5, but your size member function would need to return 7. I think the formula is probably just "underlying size() plus underlying size devided by step size", but double-check that.

`operator[]` will need to do some divisions and/or modulo operations (involving step size and size of the inserted range) to map the requested position either into the underlying range or into the inserted range.

When you start working on this, ignore the view_functor stuff, just work with the struct. here's a rough draft

```cpp

template <std::ranges::RandomAccessRange urngt_t, std::ranges::RandomAccessRange inserted_rng_t>
    requires std::ranges::View<urng_t> && std::ranges::SizedRange<urng_t> &&
             std::ranges::View<inserted_rng_t> && std::ranges::SizedRange<inserted_rng_t> &&
             std::Same<reference_t<urng_t>, reference_t<inserted_rng_t>
class view_interleave : public ranges::view_interface<view_interleave<urng_t, inserted_rng_t>>
{
private:
    urng_t urange;
    size_t step_size{};
    inserted_rng_t inserted_range;


public:
    using reference         = reference_t<urng_t>;
    using const_reference   = detail::transformation_trait_or_t<seqan3::reference<urng_t const>, void>;
    using value_type        = value_type_t<urng_t>;
    using size_type         = size_type_t<urng_t>
    using difference_type   = difference_type_t<urng_t>;
    using iterator          = detail::random_access_iterator<view_interleave>;
    using const_iterator    = detail::random_access_iterator<view_interleave const>;

// defaulted constructors
//...

    view_interleave(urng_t _urange, size const _step_size, inserted_rng_t _inserted_range) :
        urange{_urange}, step_size{_step_size}, inserted_range{_inserted_range}
    {}

// begin(), begin() const, cbegin() const, end(), end() const, cend() const
// see view_translation for how to do these 

    size_type size()
    {
    //...
    }

    size_type size() const
    {
    //...
    }


    reference operator[](size_type const i)
    {
    //...
    }

    const_reference operator[](size_type const i) const
    {
    //...
    }
};
```

The test it like this:
```cpp
std::string u{"FOOBARBAXBAT"};
std::string i{"in"};
size_t s = 1; //2, 3, 4, 5, 6, 7, 8, 9....

auto v = detail::view_interleave{view::all(u), s, view::all(i)};
// print v, verify v.size(), ...
```

When all of this works we can look at the rest of the implementation together.
